database:
  connection_string: "postgresql://postgres:post2508@localhost:5432/cricket_dw"

data:
  # The generic data_loader will execute this specific query
  sql_query: >
    SELECT 
        t.date_key, 
        t.team_total_runs, 
        t.team_run_rate, 
        t.total_wickets_lost,
        CASE WHEN dm.winner = dt.team_name THEN 1 ELSE 0 END AS target
    FROM feature_store.team_match_features t
    JOIN gold_analytics.dim_match dm 
        ON t.match_key = dm.match_key
    JOIN gold_analytics.dim_team dt 
        ON t.team_key = dt.team_key
    ORDER BY t.date_key ASC

  temporal_col: "date_key"
  train_test_split_date: 20230101
  target_col: "target"

  features:
    - team_total_runs
    - team_run_rate
    - total_wickets_lost

model:
  type: "xgboost"
  params:
    n_estimators: 200
    max_depth: 6
    learning_rate: 0.05
    random_state: 42

paths:
  model_save_path: "./artifacts/cricket_xgb_model.pkl"